networks:
  default:
    external: true
    name: my_network

services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "3233:5432"
    networks:
      - default

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - default

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.services.celery worker --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - default

volumes:
  postgres-data:
