services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - ../cipher/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "3233:5432"