"""add relationship

Revision ID: 112f3b40e547
Revises: 3080aad3d523
Create Date: 2024-07-01 13:14:44.725960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112f3b40e547'
down_revision: Union[str, None] = '3080aad3d523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'current_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rating', 'reputation',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'hearts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'clue',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.alter_column('users', 'clue',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'hearts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'subscription_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rating', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rating', 'reputation',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rating', 'current_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
