"""add defalt heart and clue

Revision ID: 13ab2ab4e06d
Revises: b1b0892bb5e2
Create Date: 2024-07-09 11:03:45.720893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ab2ab4e06d'
down_revision: Union[str, None] = 'b1b0892bb5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
