"""add subscription_status bool-false

Revision ID: 3080aad3d523
Revises: b9fdb066eb1c
Create Date: 2024-07-01 11:20:06.647212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3080aad3d523'
down_revision: Union[str, None] = 'b9fdb066eb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
