"""change name

Revision ID: 5d3dda92c883
Revises: eba101fcbf32
Create Date: 2024-06-30 14:32:49.391836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3dda92c883'
down_revision: Union[str, None] = 'eba101fcbf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_length', sa.Integer(), nullable=True),
    sa.Column('hint', sa.Integer(), nullable=True),
    sa.Column('degree_hint', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reputation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hint', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('degree_hint', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reputation_pkey')
    )
    op.drop_table('levels')
    # ### end Alembic commands ###
