"""make global_settings

Revision ID: 7654d5e5ca0b
Revises: ef92dbc8c46b
Create Date: 2024-07-05 10:59:42.996015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7654d5e5ca0b'
down_revision: Union[str, None] = 'ef92dbc8c46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.alter_column('levels', 'code_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('levels', 'hint',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('levels', 'degree_hint',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'degree_hint',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('levels', 'hint',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('levels', 'code_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('settings')
    # ### end Alembic commands ###
