"""add Rating Time Tables

Revision ID: bbbd44daf086
Revises: 7a64d08973c5
Create Date: 2024-07-22 12:24:53.172860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbd44daf086'
down_revision: Union[str, None] = '7a64d08973c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating-forever',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating-month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating-week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rating')
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reputation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_level'], ['levels.id'], name='rating_current_level_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rating_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rating_pkey')
    )
    op.drop_table('rating-week')
    op.drop_table('rating-month')
    op.drop_table('rating-forever')
    # ### end Alembic commands ###
