"""fix ForigenKey3

Revision ID: e3db5f18c905
Revises: 7b6cc0d23f75
Create Date: 2024-07-26 15:40:21.124481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3db5f18c905'
down_revision: Union[str, None] = '7b6cc0d23f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
