"""add relationship

Revision ID: e573598e4224
Revises: fc1bcdb0c473
Create Date: 2024-07-20 00:11:11.567155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e573598e4224'
down_revision: Union[str, None] = 'fc1bcdb0c473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('attempts', sa.Integer(), nullable=False))
    op.drop_column('levels', 'hint')
    op.drop_column('subscription', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('levels', sa.Column('hint', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('levels', 'attempts')
    # ### end Alembic commands ###
